### ISSUE TITLE
If running multiple instances, does Chrome need to be maximized?

### ISSUE THREAD

**Issue by josephroosen** [Hari-Nagarajan/fairgame#409]
Simple question and not a bug. I am just interested to know if fairgame requires the browser instances that it creates to be maximized or can they be minimized? 

If they have to be maximized, do they all need to have to be at the top of the Z axis and without any windows on top of them(even each other)?

Thank you for your time and your work!

**Comment by DakkJaniels** [comment]
You cannot have the window minimized. It takes a screenshot before starting to click buttons, which should help avoid errors due to this, but better to just leave it open. It does not need to be maximized. Multiple instances are not officially supported, no idea if windows can be on top of one another, but I think the screenshot issue should help resolve that as well.
