### ISSUE TITLE
Amazon giving me dogs

### ISSUE THREAD

**Issue by mateuszdrab** [Hari-Nagarajan/fairgame#420]
Hey guys

Thanks for the bot! I finally managed to order a 3090 for myself, but I was still chasing a Strix so I could cancel this one.

Wanted to report that running the bot for 4+ hours in the cloud with the default refresh rate chasing 3 cards end up in me getting the 'dogs' whenever I go to the offer page of the product. This persists even when changing IP and in fact affects me even on my laptop. Hope it's just some kind of temporary throttling. 

Anyone aware of this?

**Comment by mateuszdrab** [comment]
Note to self, I'm useless #396

**Comment by shroyhammer** [comment]
> 
> 
> Note to self, I'm useless #396

Yaus my friend, and I as well!
You fix your dogs?   I don't mean neutered... (☞ﾟヮﾟ)☞       ☜(ﾟヮﾟ☜) 
The picture on the top is what your config asin numbers should look like.  You can see hoe somehow amazon changed my asin numbers and that's how you get the cute puppers instead of addictive heroine GPU's.
Please let me know if this works for you, I'm wondering if this is a fix or a separate issue for rare pupper disease.
Thanks,

![FIX](https://user-images.githubusercontent.com/79087957/111821993-81dfba00-88a0-11eb-9b5e-00c6d1f956fa.png)
![saw dogs terminal](https://user-images.githubusercontent.com/79087957/111821996-82785080-88a0-11eb-8378-56e2b8675f69.png)
![saw dogs](https://user-images.githubusercontent.com/79087957/111821999-82785080-88a0-11eb-8158-8c0cbcb5dc60.png)
![saw dogs config](https://user-images.githubusercontent.com/79087957/111822000-8310e700-88a0-11eb-951b-475d770ef40b.png)
