### ISSUE TITLE
Does not recognize the price tag

### ISSUE THREAD

**Issue by Orsobrugno** [Hari-Nagarajan/fairgame#468]
**Describe the bug**
After checking stock for items, it says "Failed to load price for... going to next ASIN

![image](https://user-images.githubusercontent.com/77671548/105030042-7d8b5200-5a53-11eb-9fc2-9a58f9b33efd.png)

 - OS: [win10]
 - Browser [chrome]

**Comment by tomprsn** [comment]
@Orsobrugno  I believe this has to do with how html elements tags vary on different country versions of Amazon. I presume you're not using amazon.com? I had to manually inspect the element of the price and modify `stores/amazon.py` to recognise the price correctly. 

E.g. around like 642:

```
while True:
           prices = self.driver.find_elements_by_xpath(
                '//*[@class="a-size-large a-color-price olpOfferPrice a-text-bold"]'
            )
            
            # this is what I added
            if not prices:
                prices = self.driver.find_elements_by_xpath(
                '//*[@id="priceblock_ourprice"]'
                )
           # end of what I added

            if prices:
                break
            if time.time() > timeout:
                log.info(f"failed to load prices for {asin}, going to next ASIN")
                return False
```

I found that the price element's id was `priceblock_ourprice` by inspecting the element then ctrl+f for the price of an item that's in stock, iterating through each one until it was the main price in the middle of the screen, then took the id from that. It might be called something differently to you. I think the layout of the Amazon page will vary a lot based on what country you're using, and potentially whether you're in any A/B UI test or not, so this is only something that can be dealt with on a case by case basis presumably, which is why there's not a fix for it in master. 

You might have to do something similar to detect the right submit button, it was clicking the wrong one on mine. But the rest of the process after that works fine

**Comment by DakkJaniels** [comment]
Covered by #503
