### ISSUE TITLE
Amazon.it - Ordine in preparazione is not a known title

### ISSUE THREAD

**Issue by alesgt89** [Hari-Nagarajan/fairgame#476]
On Amazon.it the flow breaks because of a new page, see log and print attached.
(Win10, Google Chrome)
![screenshot-unknown-title_01-29-2021_15_16_07](https://user-images.githubusercontent.com/26802826/106288102-e474ec00-6247-11eb-988f-86be0fa3626a.png)
[fairgame.log](https://github.com/Hari-Nagarajan/fairgame/files/5894410/fairgame.log)

**Comment by unapproachable** [comment]
I've added "Ordine in preparazione" as a known page title.  The bot will still stop on this page, but it will send you a notification so you can pick.  The bot can't pick the address for you, so it'll require manual intervention.  It's in a branch now, will be in development soon, and in the next release.

If anyone has any other page titles for EU or other properties, please send them in because this is a new page to the bot and we need to build up the collection of page names.  Also, if anyone gets this page, save the source, clean the personal info, and either upload it here or DM someone with the developer role on Discord.

**Comment by alesgt89** [comment]
@unapproachable Thanks mate, sure I'll add every other unknown page title I get. 

Anyway by using the feature/xpath-updates version now I'm not even able to add to cart anymore on Amazon.it, because the bot gets stuck on the product page with "failed to load prices". 
[fairgame.log](https://github.com/Hari-Nagarajan/fairgame/files/5898173/fairgame.log)
![print](https://user-images.githubusercontent.com/26802826/106359879-a47c3a80-6315-11eb-8526-18e0d7073dd8.png)

I had found the exact same behavior on Amazon.de / fr / es / uk during the past week, I think using both the dev branch and the master version if I remember right. Now this affects Amazon.it too. 

The master version on Amazon.it is still able to get the price, but ofc same problem not recognizing "Ordine in preparazione".

**Comment by megalomenyak** [comment]
For Amazon.com.tr i've added all the titles, texts rtx..bot adding the items cart but last dont check-out? And items price max dont work. Any help?

![IMG_20210130_164615](https://user-images.githubusercontent.com/77583184/106365989-1cfcee80-634a-11eb-96aa-4de206e165b1.jpg)

**Comment by alesgt89** [comment]
I will close the original issue because is resolved, @megalomenyak please create a new one for Amazon.tr.

Thanks
