### ISSUE TITLE
Multi-item listings such as PS5 are defaulting to first item in list rather than ASIN:

### ISSUE THREAD

**Issue by SirDystic** [Hari-Nagarajan/fairgame#501]
![image](https://user-images.githubusercontent.com/74874762/107645509-aed0f980-6c70-11eb-9b25-60e9c7378ff0.png)

Seeing a similar ASIN issue with German, France and Spain ASINs for the PS5. Trying to buy a PS5 digital or normal, the ASIN url is directed to focus on a the first item on the list instead of the console:

So https://www.amazon.de/dp/B08H93ZRK9/ref=olp_dp_redir or https://www.amazon.es/dp/B08KJF2D25/#aod focuses on the wrong item

To see the correct ASIN this link now seems to be required: https://www.amazon.de/dp/B08H93ZRK9/?th=1

Also a minor issue on the Amazon Italy site:

"ERROR Ordine in preparazione is not a known title, please create issue indicating the title with a screenshot of page"

**Comment by Guilhem30** [comment]
having the same problem but unfortunately "https://www.amazon.de/dp/B08H93ZRK9/?th=1" doesn't seem to fix it for me.
I think we are going to need an additional click from the bot

**Comment by SirDystic** [comment]
What URL do you see in the address bar when you manually click on the correct item then?

**Comment by Guilhem30** [comment]
seeing the url you mentionned but pasting it on a new tab doesn't allow to reach the page with the PS5 pre-selected, it goes back to the controller. Seems like the only way is to click the button to switch product after loading the page.

**Comment by unapproachable** [comment]
I've verified this and it's pretty annoying.  We're open to solutions and if anyone finds a URL or parameter that helps, please post here.  Specifying the 'correct' ASIN URL clearly does nothing in this scenario :-(

**Comment by Guilhem30** [comment]
After some more testing it seems to pick the first product on the page and not the ASIN asked because the product is not on stock.
If you try to get the Camera for example on the DE website : https://www.amazon.de/dp/B08H9724CC/#AOD it works and doesn't default back to the controller.

Not a python developer but I think the solution would be to add a check after loading the AOD webpage and if the ASIN received isn't the one asked, consider the product unavailable and wait the delay before doing another check.

**Comment by unapproachable** [comment]
@Guilhem30 Can you verify that if the product *IS* available, it is guaranteed to be the one loaded if it's the ASIN in the URL?  I know I can check, but I'm hoping since you may have more experience testing it, you can verify that so we can make that enhancement where (assuming we can detect it isn't the one loaded), that it's not in stock.

Also, this is why everyone should manage their "min" price as well as their "max" price

**Comment by Guilhem30** [comment]
not sure i understand your question. As i posted above it works with the camera https://www.amazon.de/dp/B08H9724CC/#AOD
which is not the first product in the selector. Can't check with the actual console obviously. 
The min-max price prevent from buying the wrong product but i'm not sure if the issue prevent from buying the correct product when it comes back in stock or not.

**Comment by Guilhem30** [comment]
I was running on headless mode before and didn't notice this but the bot keep reloading the same page to evaluate offers if they don't match with the price range. So I think this issue will not prevent it from actually buying the console when it comes back in stock because amazon presumably will stop redirecting.

I guess it's a small issue which is mostly confusing because the bot says he found offers when there are none.

A fix could still be useful however because it could cause the bot to order the wrong product is by some bad luck prices match.
Maybe it's possible to check the form values in the flyout, for example :
<input type="hidden" name="metric-asin.B08H96W864" value="1">
The asin should match with the one the bot requested before adding to basket.

**Comment by unapproachable** [comment]
Okay, it took a while to get around to it, but there's a version of the 0.6.0 release that has a single fix for this issue.  I can't test it well because I only have the one use case.  For anyone still interested in this issue, the code is here:

https://github.com/Hari-Nagarajan/fairgame/tree/feature/multi-item-listing

Thanks to Guilhem30 for the node value to look for.  It's certainly not faster to verify that the offers are correctly associated with the ASIN requested, but probably a good safeguard.  Optimizations are possible, but brute force seemed like the best approach to at least test this fix for those who experience the issue.

**Comment by docbt** [comment]
Well done. Your fix works.

I see "0.6.0|INFO|Offers don't correspond to the ASIN ..." with this branch.

**Comment by Guilhem30** [comment]
Yep it seems to work. Although i've had no success trying to buy a ps5 yet so i can't confirm that it 100% allow to buy one.

**Comment by SirDystic** [comment]
Just to note that I have successfully purchased a PS5 from a tabbed listing so this is working right now as of build 0.60

**Comment by DakkJaniels** [comment]
Great! thank you for the update @SirDystic
