### ISSUE TITLE
Multiple istance in different amazon fake notification

### ISSUE THREAD

**Issue by giuseppe99barchetta** [Hari-Nagarajan/fairgame#525]
When I start new session with same ASIN list but different Amazon country the script find on the firts script all ASIN at 1€, i'm doing something wrong?

**Comment by DakkJaniels** [comment]
Multiple instances are not a supported usage case.

**Comment by giuseppe99barchetta** [comment]
> Multiple instances are not a supported usage case.

Github description says that are supported:

> Can I run multiple instances of the bot?
> 
> Yes. For example you can run one instance to check stock on Best Buy and a separate instance to check stock on Amazon. Bear in mind that if you do this you may end up with multiple purchases going through at the same time.

**Comment by DakkJaniels** [comment]
Yes - the intent of that paragraph was that you can run a Best Buy instance and an Amazon instance, when Best Buy was supported. This was fixed in the Wiki, but the change did not make it into the readme yet. It has been updated in the development version of the readme.

![image](https://user-images.githubusercontent.com/6080734/109326464-3b5ce980-7825-11eb-8b61-797bf4d86987.png)

![image](https://user-images.githubusercontent.com/6080734/109326512-4adc3280-7825-11eb-8252-54dc3c402cb7.png)

**Comment by giuseppe99barchetta** [comment]
> Yes - the intent of that paragraph was that you can run a Best Buy instance and an Amazon instance, when Best Buy was supported. This was fixed in the Wiki, but the change did not make it into the readme yet. It has been updated in the development version of the readme.
> 
> ![image](https://user-images.githubusercontent.com/6080734/109326464-3b5ce980-7825-11eb-8b61-797bf4d86987.png)
> 
> ![image](https://user-images.githubusercontent.com/6080734/109326512-4adc3280-7825-11eb-8252-54dc3c402cb7.png)

Ok, I'm sorry.

Thanks a lot
