### ISSUE TITLE
Multiple items at the same time (no filtering)

### ISSUE THREAD

**Issue by Jarradmorden** [Hari-Nagarajan/fairgame#610]
How would I configure multiple items at the same time, because if I use the list it will just filter each one, one by one, so other people's bots will be faster?

I would like to run multiple pages at the same time

**Comment by DakkJaniels** [comment]
It is not configured to run concurrent checks.

**Comment by Jarradmorden** [comment]
I would defiantly recommend this to be added because as an example if someone has a bot set to one page on their let's say custom bot it will be sold out so if I am filtering through 5 cards it will already be too late, this happened on the RTX 3090 I visited the drop 1 second after link drop and it had gone.

**Comment by Jarradmorden** [comment]
Can this file be duplicated?

**Comment by DakkJaniels** [comment]
Design decision to not run concurrent checks. You are welcome to modify the code to support that if you want it. You can copy the whole folder and rerun all the install steps (except for installing Python) to run additional instances of the program, however this is not supported.

**Comment by Jarradmorden** [comment]
Okay I appreciate your help, thanks for opening up the project though!

**Comment by Jarradmorden** [comment]
May I ask why you wouldn't want to run concurrent checks?

**Comment by DakkJaniels** [comment]
Multiple reasons:

1. Because you are not the only person running the bot and we are not interesting in DDoSing when many people decide they need to run 100s of products at the same time
2. There is no proxy support and no plans to add proxy support, so you are just increasing the likelihood of getting banned by Amazon
3. It is slightly more complex to add asynchronous checks
