### ISSUE TITLE
1-click buy 

### ISSUE THREAD

**Issue by CKocoglu** [Hari-Nagarajan/fairgame#613]
There is a button that allow us to buy product with 1 click. Can you add this path to fairgame ?

**Comment by DakkJaniels** [comment]
No - hitting the Buy It Now button isn't 1-click. Sometimes there are other offers that pop up after you hit buy it now, that you need to hit no thanks on, sometimes some JS code needs to run, sometimes other things happen, sometimes there is nothing in the buy box or buy it now spot, but all the products are located in the offers page, sometimes etc., etc., etc.. If someone has an implementation of using buy it now that is functional and doesn't miss stuff that doesn't enter the buy box, they should submit a PR for it. Otherwise, everyone should stop suggesting it.

**Comment by CKocoglu** [comment]
Okay , the bot isn't buying right ? i need to do it manually like choose
address and paying method? Because terminal says like this. If somehow i
can change it auto buy how can i do it?

DakkJaniels ***@***.***>, 26 Mar 2021 Cum, 14:26 tarihinde
şunu yazdı:

**Comment by DakkJaniels** [comment]
If you setup the bot correctly, and follow the instructions, it shouldn't be asking you for shipping address.

**Comment by CKocoglu** [comment]
Got it. [image: image.png][image: image.png]
If i set this variable True.Will it select default address? Because i have
only 1 address in my account. So will it work like this?

DakkJaniels ***@***.***>, 26 Mar 2021 Cum, 20:09 tarihinde
şunu yazdı:
