### ISSUE TITLE
[Question] Is it bad to run multiple instances of Fairgame from same folder?

### ISSUE THREAD

**Issue by Spareo** [Hari-Nagarajan/fairgame#625]
I modified the fairgame code to allow me to pass in a custom auto-buy config file instead of just using the hard coded `amazon_config.json` file so I could just create multiple configs in one place and run multiple instances of the bot. 

The bot appears to start up and run normally when I do this, but I'm wondering if there are any unforeseen consequences that I'm aware of with doing this?

**Comment by DakkJaniels** [comment]
We don't support multiple instances. No idea.

**Comment by Spareo** [comment]
@DakkJaniels I know its not officially supported. I guess I'm just wondering why its not officially supported? Is it due to a technical reason, or there just hasn't been an ask for it?

**Comment by DakkJaniels** [comment]
Lots of people ask about running multiple bots. Obviously with more instances, you are hitting Amazon way more and are more likely to run into issues with them blocking you because of it, so our stance is not to run multiple bots to reduce risk of this occurring.

Regarding technical issues of running from one folder, I thought there were issues with re-using the chrome profile, but I don't know now, since it seems you were able to do it. But regardless, not looking into it and no plans to do so.

**Comment by gtrak** [comment]
I was able to do it with multiple chrome profiles (1 per config) by passing in a CLI flag. Conveniently the config framework allows env-var expansion.

```
diff --git a/config/fairgame.conf b/config/fairgame.conf
index 0911373..6cd6dd7 100644
--- a/config/fairgame.conf
+++ b/config/fairgame.conf
@@ -1,6 +1,6 @@
 {
   "FAIRGAME": {
-    "profile_name": ".profile-amz"
+    "profile_name": `$FAIRGAME_PROFILE`
   },
   "AMAZON": {
     "SIGN_IN_TEXT": [
@@ -130,4 +130,4 @@
       "Select a shipping address"
     ]
   }
-}
\ No newline at end of file
+}```
