### ISSUE TITLE
With some ASINS I get an error, this is due to the bot adding â€Ž to the start of some ASINS in the URL.

### ISSUE THREAD

**Issue by vezzela** [Hari-Nagarajan/fairgame#809]
{
  "asin_groups": 1,
  "asin_list_1": ["‎‎B08L8L9TCZ"],
  "reserve_min_1": 500,
  "reserve_max_1": 1000,
  "amazon_website": "smile.amazon.com"
}

If I use this ASIN ill get thrown to this page: https://smile.amazon.com/dp/â€ŽB08L8L9TCZ
Instead of just:  https://smile.amazon.com/dp/B08L8L9TCZ

it only does these for a few ASINS, I do not know what the issue is, why is it adding â€Ž to the start of the ASIN on the url?

**Comment by SalvadorSTM** [comment]
Why are random characters (e.g., â€Ž) showing up in the URL when the bot is doing a stock check? Is the bot broken??

The random characters are showing up because you added them to the config file from wherever you copied the ASIN from. What? You are saying you didn’t add them to the config file? If you change the encoding in your text editor to ANSI they will show up. In UTF-8 encoding that is encoded as “left-to-right mark”, which is not a visible character in UTF-8. To fix this, delete the ASIN, including the brackets, and retype it manually (or switch to ANSI encoding and delete the extra characters).
![image](https://user-images.githubusercontent.com/26339812/125027070-a4fec700-e053-11eb-90e8-e6e1bca69222.png)
